# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import engagement_pb2 as engagement__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engagement_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddComment = channel.unary_unary(
                '/engagement.v1.EngagementService/AddComment',
                request_serializer=engagement__pb2.AddCommentRequest.SerializeToString,
                response_deserializer=engagement__pb2.AddCommentResponse.FromString,
                _registered_method=True)
        self.ListComments = channel.unary_unary(
                '/engagement.v1.EngagementService/ListComments',
                request_serializer=engagement__pb2.ListCommentsRequest.SerializeToString,
                response_deserializer=engagement__pb2.ListCommentsResponse.FromString,
                _registered_method=True)
        self.SetLike = channel.unary_unary(
                '/engagement.v1.EngagementService/SetLike',
                request_serializer=engagement__pb2.SetLikeRequest.SerializeToString,
                response_deserializer=engagement__pb2.SetLikeResponse.FromString,
                _registered_method=True)
        self.GetEngagement = channel.unary_unary(
                '/engagement.v1.EngagementService/GetEngagement',
                request_serializer=engagement__pb2.GetEngagementRequest.SerializeToString,
                response_deserializer=engagement__pb2.GetEngagementResponse.FromString,
                _registered_method=True)


class EngagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLike(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEngagement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddComment': grpc.unary_unary_rpc_method_handler(
                    servicer.AddComment,
                    request_deserializer=engagement__pb2.AddCommentRequest.FromString,
                    response_serializer=engagement__pb2.AddCommentResponse.SerializeToString,
            ),
            'ListComments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListComments,
                    request_deserializer=engagement__pb2.ListCommentsRequest.FromString,
                    response_serializer=engagement__pb2.ListCommentsResponse.SerializeToString,
            ),
            'SetLike': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLike,
                    request_deserializer=engagement__pb2.SetLikeRequest.FromString,
                    response_serializer=engagement__pb2.SetLikeResponse.SerializeToString,
            ),
            'GetEngagement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEngagement,
                    request_deserializer=engagement__pb2.GetEngagementRequest.FromString,
                    response_serializer=engagement__pb2.GetEngagementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engagement.v1.EngagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engagement.v1.EngagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engagement.v1.EngagementService/AddComment',
            engagement__pb2.AddCommentRequest.SerializeToString,
            engagement__pb2.AddCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engagement.v1.EngagementService/ListComments',
            engagement__pb2.ListCommentsRequest.SerializeToString,
            engagement__pb2.ListCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engagement.v1.EngagementService/SetLike',
            engagement__pb2.SetLikeRequest.SerializeToString,
            engagement__pb2.SetLikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEngagement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engagement.v1.EngagementService/GetEngagement',
            engagement__pb2.GetEngagementRequest.SerializeToString,
            engagement__pb2.GetEngagementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
