services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./env/db.env
      - ./env/backend.env
    restart: unless-stopped
    volumes:
      - ./uploads:/var/app/upload
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend

  db:
    image: postgres:16
    env_file:
      - ./env/db.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d
      - backend-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  backend-postgres-data:
