apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: third-library
type: Opaque
stringData:
  POSTGRES_USER: auth
  POSTGRES_PASSWORD: auth
  POSTGRES_DB: auth
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-engagement-secret
  namespace: third-library
type: Opaque
stringData:
  POSTGRES_USER: engagement
  POSTGRES_PASSWORD: engagement
  POSTGRES_DB: engagement
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: third-library
type: Opaque
stringData:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: minio123
