# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'content.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontent.proto\x12\ncontent.v1\"\x85\x01\n\x07\x43ontent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x10\n\x08\x66ilename\x18\x05 \x01(\t\x12\x12\n\nsize_bytes\x18\x06 \x01(\x03\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\"k\n\rUploadRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t\x12\x12\n\nfile_bytes\x18\x05 \x01(\x0c\"6\n\x0eUploadResponse\x12$\n\x07\x63ontent\x18\x01 \x01(\x0b\x32\x13.content.v1.Content\" \n\nGetRequest\x12\x12\n\ncontent_id\x18\x01 \x01(\t\"G\n\x0bGetResponse\x12$\n\x07\x63ontent\x18\x01 \x01(\x0b\x32\x13.content.v1.Content\x12\x12\n\nfile_bytes\x18\x02 \x01(\x0c\"4\n\x0bListRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\"K\n\x0cListResponse\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.content.v1.Content\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\xc4\x01\n\x0e\x43ontentService\x12?\n\x06Upload\x12\x19.content.v1.UploadRequest\x1a\x1a.content.v1.UploadResponse\x12\x36\n\x03Get\x12\x16.content.v1.GetRequest\x1a\x17.content.v1.GetResponse\x12\x39\n\x04List\x12\x17.content.v1.ListRequest\x1a\x18.content.v1.ListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTENT']._serialized_start=30
  _globals['_CONTENT']._serialized_end=163
  _globals['_UPLOADREQUEST']._serialized_start=165
  _globals['_UPLOADREQUEST']._serialized_end=272
  _globals['_UPLOADRESPONSE']._serialized_start=274
  _globals['_UPLOADRESPONSE']._serialized_end=328
  _globals['_GETREQUEST']._serialized_start=330
  _globals['_GETREQUEST']._serialized_end=362
  _globals['_GETRESPONSE']._serialized_start=364
  _globals['_GETRESPONSE']._serialized_end=435
  _globals['_LISTREQUEST']._serialized_start=437
  _globals['_LISTREQUEST']._serialized_end=489
  _globals['_LISTRESPONSE']._serialized_start=491
  _globals['_LISTRESPONSE']._serialized_end=566
  _globals['_CONTENTSERVICE']._serialized_start=569
  _globals['_CONTENTSERVICE']._serialized_end=765
# @@protoc_insertion_point(module_scope)
