# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import statistics_pb2 as statistics__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in statistics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatisticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordInteraction = channel.unary_unary(
                '/statistics.v1.StatisticsService/RecordInteraction',
                request_serializer=statistics__pb2.RecordInteractionRequest.SerializeToString,
                response_deserializer=statistics__pb2.RecordInteractionResponse.FromString,
                _registered_method=True)
        self.GetContentStats = channel.unary_unary(
                '/statistics.v1.StatisticsService/GetContentStats',
                request_serializer=statistics__pb2.GetContentStatsRequest.SerializeToString,
                response_deserializer=statistics__pb2.GetContentStatsResponse.FromString,
                _registered_method=True)


class StatisticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecordInteraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContentStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordInteraction': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordInteraction,
                    request_deserializer=statistics__pb2.RecordInteractionRequest.FromString,
                    response_serializer=statistics__pb2.RecordInteractionResponse.SerializeToString,
            ),
            'GetContentStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContentStats,
                    request_deserializer=statistics__pb2.GetContentStatsRequest.FromString,
                    response_serializer=statistics__pb2.GetContentStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statistics.v1.StatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('statistics.v1.StatisticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatisticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordInteraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.v1.StatisticsService/RecordInteraction',
            statistics__pb2.RecordInteractionRequest.SerializeToString,
            statistics__pb2.RecordInteractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContentStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.v1.StatisticsService/GetContentStats',
            statistics__pb2.GetContentStatsRequest.SerializeToString,
            statistics__pb2.GetContentStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
