# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statistics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'statistics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\rstatistics.v1\"\x82\x01\n\x18RecordInteractionRequest\x12\x12\n\ncontent_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12,\n\x04type\x18\x03 \x01(\x0e\x32\x1e.statistics.v1.InteractionType\x12\x13\n\x0boccurred_at\x18\x04 \x01(\x03\"0\n\x19RecordInteractionResponse\x12\x13\n\x0brecorded_id\x18\x01 \x01(\t\"c\n\x0c\x43ontentStats\x12\r\n\x05views\x18\x01 \x01(\x03\x12\x11\n\tdownloads\x18\x02 \x01(\x03\x12\x14\n\x0cunique_users\x18\x03 \x01(\x03\x12\x1b\n\x13last_interaction_at\x18\x04 \x01(\x03\",\n\x16GetContentStatsRequest\x12\x12\n\ncontent_id\x18\x01 \x01(\t\"E\n\x17GetContentStatsResponse\x12*\n\x05stats\x18\x01 \x01(\x0b\x32\x1b.statistics.v1.ContentStats*m\n\x0fInteractionType\x12 \n\x1cINTERACTION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15INTERACTION_TYPE_VIEW\x10\x01\x12\x1d\n\x19INTERACTION_TYPE_DOWNLOAD\x10\x02\x32\xdd\x01\n\x11StatisticsService\x12\x66\n\x11RecordInteraction\x12\'.statistics.v1.RecordInteractionRequest\x1a(.statistics.v1.RecordInteractionResponse\x12`\n\x0fGetContentStats\x12%.statistics.v1.GetContentStatsRequest\x1a&.statistics.v1.GetContentStatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTERACTIONTYPE']._serialized_start=436
  _globals['_INTERACTIONTYPE']._serialized_end=545
  _globals['_RECORDINTERACTIONREQUEST']._serialized_start=36
  _globals['_RECORDINTERACTIONREQUEST']._serialized_end=166
  _globals['_RECORDINTERACTIONRESPONSE']._serialized_start=168
  _globals['_RECORDINTERACTIONRESPONSE']._serialized_end=216
  _globals['_CONTENTSTATS']._serialized_start=218
  _globals['_CONTENTSTATS']._serialized_end=317
  _globals['_GETCONTENTSTATSREQUEST']._serialized_start=319
  _globals['_GETCONTENTSTATSREQUEST']._serialized_end=363
  _globals['_GETCONTENTSTATSRESPONSE']._serialized_start=365
  _globals['_GETCONTENTSTATSRESPONSE']._serialized_end=434
  _globals['_STATISTICSSERVICE']._serialized_start=548
  _globals['_STATISTICSSERVICE']._serialized_end=769
# @@protoc_insertion_point(module_scope)
